/////////////////////////////////////
/////////////////////////////////////
/////////////////////////////////////
//WARNING
//This file has been autogenerated.
//Do NOT make modifications directly to it as they will be overwritten!
/////////////////////////////////////
/////////////////////////////////////
/////////////////////////////////////

#ifndef QUANTICO_GETDATA_PROXY_H
#define QUANTICO_GETDATA_PROXY_H

#include <ComponentAPI.h>
#include <ApplicationListenerAPI.h>
#include <ControlAIAspectAPI.h>
#include <DebugUIListenerAPI.h>
#include <MissionEditorAPI.h>
#include <MissionEditorListenerAPI.h>
#include <MissionListenerAPI.h>
#include <WeaponSystemAspectListenerAPI.h>
#include <WorldListenerAPI.h>

GEARS_EXPORT void GEARS_API RegisterAPI_v6(APIManager_RegisterAPI_Func_v6 register_api);

#endif
