/////////////////////////////////////
/////////////////////////////////////
/////////////////////////////////////
//WARNING
//This file has been autogenerated.
//Do NOT make modifications directly to it as they will be overwritten!
/////////////////////////////////////
/////////////////////////////////////
/////////////////////////////////////

#ifndef QUANTICO_GETDATA_MOCK_H
#define QUANTICO_GETDATA_MOCK_H

#include <ComponentAPI.h>
#include <ApplicationListenerAPI.h>
#include <ControlAIAspectAPI.h>
#include <DebugUIListenerAPI.h>
#include <MissionEditorAPI.h>
#include <MissionEditorListenerAPI.h>
#include <MissionListenerAPI.h>
#include <WorldListenerAPI.h>


#endif
