#include "Quantico_GetData.h"
#include "Version.h"
#include "Gears.h"
#include "ComponentDirector.h"
#include <ConnectToSQL.h>
#include <thread>

int messageID = 0;
//std::thread opThread;

//Note:
//This file is partially autogenerated
//It is safe to make modifications to most of the file, however please don't modify the API function signatures
APIResult GEARS_API Component_Initialize(_In_ const char* component_folder)
{
  //GEARS NOTE: Use this function to perform component initialization.
  //Access to other components is unavailable.
  return kAPIResult_GeneralSuccess;
}

APIResult GEARS_API Component_OnStart(_In_ APIManager_v6* api_manager, _In_ NativeModuleHandle proxy_handle)
{

  //GEARS NOTE: Use this function to connect to other components.
  //Using the specified api_manager variable, this component can request access
  //to APIs that have been registered with Gears.

  //The Gears class will take care of requesting APIs for you. See Gears.h for more details.
  Gears::InitializeAPIs(api_manager, proxy_handle);
 
  Gears::API::LogAPIv1()->SetName(Gears::API::LogAPIv1(), "Quantico_GetData");
  Gears::API::LogAPIv1()->EnableConsoleLog(Gears::API::LogAPIv1());
  Gears::API::LogAPIv1()->EnableColors(Gears::API::LogAPIv1());
  Gears::API::LogAPIv1()->EnableConsoleLog(Gears::API::LogAPIv1());
  Gears::API::LogAPIv1()->EnableDebuggerLog(Gears::API::LogAPIv1());
  Gears::API::LogAPIv1()->SetFilter(Gears::API::LogAPIv1(), kSeverityLevel_Debug);

  return kAPIResult_GeneralSuccess;
}

APIResult GEARS_API Component_OnStop()
{
  //GEARS NOTE: Use this function to perform "last chance" functionality.
  //All components are still accessible.

  //Release all APIs and set them to nullptr.
  Gears::ReleaseAPIs();

  return kAPIResult_GeneralSuccess;
}

APIResult GEARS_API Component_Shutdown()
{
  //GEARS NOTE: Use this function to cleanup any resources that were allocated.
  //This component's shared library is about to be unloaded.
  //Access to other components is unavailable.
  return kAPIResult_GeneralSuccess;
}

APIResult GEARS_API Component_IsParallelizable(_Out_ bool32_t* parallelizable)
{
  //GEARS NOTE: Set parallelizable to TRUE to enable this component's OnStart to be called from a spawned thread
  *parallelizable = FALSE;
  return kAPIResult_GeneralSuccess;
}

APIResult GEARS_API Component_GetName(_Inout_ int32_t* name_length, _Out_opt_ char* name)
{
  //GEARS NOTE: Use this function to fill out the name string with the name of the component.
  //Defaulted to return the official component name
  static const char* kComponentName = "Quantico_GetData";

  if(name_length == nullptr)
  {
    return kAPIResult_ParamsInvalid;
  }

  if(name == nullptr)
  {
    *name_length = static_cast<int32_t>(strlen(kComponentName) + 1);
  }
  else
  {
    strcpy_s(name, *name_length, kComponentName);
  }
  return kAPIResult_GeneralSuccess;
}

APIResult GEARS_API Component_GetVersion(_Inout_ int32_t* version_length, _Out_opt_ char* version)
{
  //GEARS NOTE: Use this function to fill out the version string with the version of the component.
  //Defaulted to return the auto generated/incremented version from Version.h
  static const char* kVersion = VERSION;

  if(version_length == nullptr)
  {
    return kAPIResult_ParamsInvalid;
  }

  if(version == nullptr)
  {
    *version_length = static_cast<int32_t>(strlen(kVersion) + 1);
  }
  else
  {
    strcpy_s(version, *version_length, kVersion);
  }
  return kAPIResult_GeneralSuccess;
}

APIResult GEARS_API MissionEditor_GetMode(_Out_ MissionEditorMode_v1* mode)
{
  return kAPIResult_GeneralSuccess;
}

APIResult GEARS_API MissionEditor_Open(_In_ const char* map_id, _In_opt_ const GeoPosition_v3* initial_position)
{
  return kAPIResult_GeneralSuccess;
}

APIResult GEARS_API MissionEditor_LoadMission(_In_ const char* mission_name, _In_ bool32_t is_multiplayer)
{
  return kAPIResult_GeneralSuccess;
}

APIResult GEARS_API MissionEditor_SelectObject(_In_ ObjectHandle_v3 object)
{
  return kAPIResult_GeneralSuccess;
}

APIResult GEARS_API MissionEditor_DeselectObject(_In_ ObjectHandle_v3 object)
{
  return kAPIResult_GeneralSuccess;
}

APIResult GEARS_API MissionEditor_CenterCameraOnObject(_In_ ObjectHandle_v3 object)
{
  return kAPIResult_GeneralSuccess;
}

APIResult GEARS_API MissionEditor_TriggerObjectContextMenu(_In_ ObjectHandle_v3 object, _In_opt_ const ScreenPosition_v3* position)
{
  return kAPIResult_GeneralSuccess;
}

APIResult GEARS_API MissionEditor_LoadEmptyMission(_In_ const char* map_id, _In_opt_ const GeoPosition_v3* initial_position)
{
  return kAPIResult_GeneralSuccess;
}

APIResult GEARS_API MissionEditor_CollapseOrbatObject(_In_ ObjectHandle_v3 object, _In_ bool32_t collapse)
{
  return kAPIResult_GeneralSuccess;
}

APIResult GEARS_API MissionEditor_IsCollapsedInOrbat(_In_ ObjectHandle_v3 object, _Out_ bool32_t* collapsed)
{
  return kAPIResult_GeneralSuccess;
}

APIResult GEARS_API MissionEditor_HasAspect(_In_ ObjectHandle_v3 object, _Out_ bool32_t* has_aspect)
{
  return kAPIResult_GeneralSuccess;
}

APIResult GEARS_API MissionEditor_GetObjectProperty(_In_ ObjectHandle_v3 object, _In_ const char* name, _Out_opt_ char* value, _Inout_ int32_t* value_length)
{
  return kAPIResult_GeneralSuccess;
}

APIResult GEARS_API MissionEditor_SetObjectProperty(_In_ ObjectHandle_v3 object, _In_ const char* name, _In_ const char* value)
{
  return kAPIResult_GeneralSuccess;
}

APIResult GEARS_API MissionListener_OnPlayerSwitchedUnits(_In_ ObjectHandle_v3 old_entity, _In_ ObjectHandle_v3 new_entity)
{
  return kAPIResult_GeneralSuccess;
}

APIResult GEARS_API MissionListener_OnMissionUnload(_In_ const char* mission_name)
{
  return kAPIResult_GeneralSuccess;
}

APIResult GEARS_API MissionListener_OnMissionStart(_In_ bool32_t restart)
{
  ComponentDirector::Get().OnMissionStart(restart);
  return kAPIResult_GeneralSuccess;
}

APIResult GEARS_API MissionListener_OnMissionLoad(_In_ const char* mission_name)
{
  return kAPIResult_GeneralSuccess;
}

APIResult GEARS_API MissionListener_OnMissionEnd(_In_ bool32_t restart)
{
  ComponentDirector::Get().OnMissionEnd(restart);
  return kAPIResult_GeneralSuccess;
}


APIResult GEARS_API ControlAIAspect_SetBlackboardVariable(_In_ ObjectHandle_v3 object, _In_ const char* variable, _In_ const char* value, _In_ int32_t value_size)
{
  return kAPIResult_GeneralSuccess;
}

APIResult GEARS_API ControlAIAspect_SetBehaviorTree(_In_ ObjectHandle_v3 object, _In_ const char* bt_name)
{
  return kAPIResult_GeneralSuccess;
}

APIResult GEARS_API ControlAIAspect_ReceiveMessage(_In_ ObjectHandle_v3 object, _In_ const char* subject, _In_ const char* parameters, _In_ int32_t parameters_size)
{
  return kAPIResult_GeneralSuccess;
}

APIResult GEARS_API ControlAIAspect_HasAspect(_In_ ObjectHandle_v3 object, _Out_ bool32_t* has_aspect)
{
  return kAPIResult_GeneralSuccess;
}

APIResult GEARS_API ControlAIAspect_GetBlackboardVariable(_In_ ObjectHandle_v3 object, _In_ const char* variable, _Out_ char* value, _Inout_ int32_t* value_size)
{
  return kAPIResult_GeneralSuccess;
}

APIResult GEARS_API ControlAIAspect_GetBehaviorTree(_In_ ObjectHandle_v3 object, _Out_ char* buffer_bt_name, _Inout_ int32_t* buffer_size)
{
  return kAPIResult_GeneralSuccess;
}

APIResult GEARS_API ApplicationListener_OnBeforeSimulation(_In_ float32_t delta)
{
  ComponentDirector::Get().OnBeforeSimulation(delta);
  return kAPIResult_GeneralSuccess;
}

APIResult GEARS_API ApplicationListener_OnAfterSimulation(_In_ float32_t delta)
{
  return kAPIResult_GeneralSuccess;
}

APIResult GEARS_API MissionEditorListener_OnObjectSelectionChange(_In_ ObjectHandle_v3 object, _In_ bool32_t selected)
{
  return kAPIResult_GeneralSuccess;
}

APIResult GEARS_API MissionEditorListener_OnObjectExpandCollapse(_In_ ObjectHandle_v3 object, _In_ bool32_t expanded)
{
  return kAPIResult_GeneralSuccess;
}

APIResult GEARS_API MissionEditorListener_OnMapExport(_In_ GeoPosition_v3 begin, _In_ GeoPosition_v3 end, _In_ float32_t scale, _In_ float32_t detail, _In_ MapExportMode_v1 mode, _In_ const MapExportInterface_v1* mei, _In_opt_ const char** layers, _In_opt_ int32_t layer_count)
{
  return kAPIResult_GeneralSuccess;
}

APIResult GEARS_API MissionEditorListener_OnClose()
{
  return kAPIResult_GeneralSuccess;
}

void GEARS_API DebugUIListener_OnRenderMainWindow()
{
    ComponentDirector::Get().OnRenderMainWindow();
}

void GEARS_API DebugUIListener_OnRenderHMDWindow()
{
}

void GEARS_API DebugUIListener_OnRenderCustomWindow()
{
    ComponentDirector::Get().OnRenderCustomWindow();
}

void GEARS_API WorldListener_OnObjectDeletion(_In_ ObjectHandle_v3 object)
{
}

void GEARS_API WorldListener_OnObjectCreation(_In_ ObjectHandle_v3 object)
{
    bool32_t has_aspect = FALSE;
    Gears::API::WeaponSystemAspectAPIv6()->HasAspect(object, &has_aspect);
    if (has_aspect != FALSE)
    {
        Gears::API::WeaponSystemAspectAPIv6()->RegisterEvent(object, MunitionEventType_v4::kMunitionEventType_fire, "Quantico_GetData"); // Be sure to change this to the name of your component
    }
    ComponentDirector::Get().OnObjectCreation(object);
}

void GEARS_API WorldListener_OnLocalObjectPromotion(_In_ ObjectHandle_v3 old_handle, _In_ ObjectHandle_v3 new_handle)
{
}

APIResult GEARS_API WeaponSystemAspectListener_OnFire(_In_ ObjectHandle_v3 shooter, _In_ ObjectHandle_v3 shot)
{
    ConnectToSQL s;
    char buffer[256];
    int32_t buffer_size = 256;
    Gears::API::ScriptAPIv3()->GetVariableName(shooter, buffer, &buffer_size);
    DateTime_v3 time;
    if (strcmp(buffer, "erightlead") == 0 || strcmp(buffer, "eright2") == 0 || strcmp(buffer, "eright3") == 0 || strcmp(buffer, "eright4") == 0
        || strcmp(buffer, "emrightlead") == 0 || strcmp(buffer, "emright2") == 0 || strcmp(buffer, "emright3") == 0 || strcmp(buffer, "emright4") == 0
        || strcmp(buffer, "eleftlead") == 0 || strcmp(buffer, "eleft2") == 0 || strcmp(buffer, "eleft3") == 0 || strcmp(buffer, "eleft4") == 0
        || strcmp(buffer, "emleftlead") == 0 || strcmp(buffer, "emleft2") == 0 || strcmp(buffer, "emleft3") == 0 || strcmp(buffer, "emleft4") == 0)
        
    {
    
    Gears::API::EnvironmentAPIv3()->GetTime(&time);
    std::stringstream stream;
    stream << buffer << "," << time.hour << ":" << time.minute << ":" << time.second;
    OutputDebugString(stream.str().c_str());
    OutputDebugString("\n");
    s.UpdateFireTable(stream.str(), messageID);
    ComponentDirector::Get().OnEnemyFire();
    messageID++;
    }
  return kAPIResult_GeneralSuccess;
}

APIResult GEARS_API WeaponSystemAspectListener_OnAmmoHit(_In_ const HitEvent_v2* hit_info)
{
  
  return kAPIResult_GeneralSuccess;
}

